services:
  mongo:
    image: mongo:8.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build: backend
    restart: always
    ports:
      - 8000:8000
    environment:
      DB_USER: root
      DB_PASSWORD: example
      DB_HOST: mongo
      FRONTEND_URL: http://localhost:8001

  frontend:
    restart: always
    build: 
      context: frontend
      args:
        REACT_APP_API_URL: http://localhost:8000
    ports:
      - 8001:80