services:
  mongo:
    image: mongo:8.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db 

  backend:
    build: backend
    restart: always
    ports:
      - 8000:8000
    environment:
      DB_USER: root
      DB_PASSWORD: example
      DB_HOST: mongo
      FRONTEND_URL: http://localhost:8001
      SECRET_KEY: 09d25e094faa6ca2552c818166b7a9563b93fa199f6f0f4caa6cf53b88e8d3e7
      ADMIN_PASSWORD: cardinal

  frontend:
    restart: always
    build: 
      context: frontend
      args:
        REACT_APP_API_URL: http://localhost:8000
    ports:
      - 8001:8001

volumes:
  mongo_data: